/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loonyquiz;

import java.awt.Color;

/**
 *
 * @author Hannah
 */
public class MainScreen extends javax.swing.JFrame
{

    /**
     * Creates new form MainScreen
     */
    public MainScreen()
    {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        butStart.setBackground(Color.ORANGE);
        if(Global.lives == 0)
        {
            labLoonQuiz.setText("Game Over!");
        }
        else
        {
            labLoonQuiz.setText("Loony Quiz");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labLoonQuiz = new javax.swing.JLabel();
        butStart = new javax.swing.JButton();
        butHiScore = new javax.swing.JButton();
        butExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(380, 500));
        setMinimumSize(new java.awt.Dimension(380, 500));

        labLoonQuiz.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labLoonQuiz.setText("Loony Quiz");

        butStart.setText("Start");
        butStart.setMaximumSize(new java.awt.Dimension(125, 65));
        butStart.setMinimumSize(new java.awt.Dimension(125, 65));
        butStart.setPreferredSize(new java.awt.Dimension(125, 65));
        butStart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butStartActionPerformed(evt);
            }
        });

        butHiScore.setText("Highscores");
        butHiScore.setMaximumSize(new java.awt.Dimension(125, 65));
        butHiScore.setMinimumSize(new java.awt.Dimension(125, 65));
        butHiScore.setPreferredSize(new java.awt.Dimension(125, 65));
        butHiScore.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butHiScoreActionPerformed(evt);
            }
        });

        butExit.setText("Exit");
        butExit.setMaximumSize(new java.awt.Dimension(125, 65));
        butExit.setMinimumSize(new java.awt.Dimension(125, 65));
        butExit.setPreferredSize(new java.awt.Dimension(125, 65));
        butExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labLoonQuiz)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butExit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butHiScore, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butStart, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(labLoonQuiz)
                .addGap(84, 84, 84)
                .addComponent(butStart, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butHiScore, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butStartActionPerformed
    {//GEN-HEADEREND:event_butStartActionPerformed
        //Load Topics
        Global.lives = 3;
        TopicScreen ts = new TopicScreen();
        ts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butStartActionPerformed

    private void butHiScoreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butHiScoreActionPerformed
    {//GEN-HEADEREND:event_butHiScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butHiScoreActionPerformed

    private void butExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butExitActionPerformed
    {//GEN-HEADEREND:event_butExitActionPerformed
        //Exit
        this.dispose();
    }//GEN-LAST:event_butExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butExit;
    private javax.swing.JButton butHiScore;
    private javax.swing.JButton butStart;
    private javax.swing.JLabel labLoonQuiz;
    // End of variables declaration//GEN-END:variables
}
