/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loonyquiz;

/**
 *
 * @author Hannah
 */
public class NexTopScreen extends javax.swing.JFrame
{

    /**
     * Creates new form NexTopScreen
     */
    public NexTopScreen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labCorrect = new javax.swing.JLabel();
        labLives = new javax.swing.JLabel();
        butTopTwo = new javax.swing.JButton();
        butTopOne = new javax.swing.JButton();
        labNextTop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NexTop");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(380, 500));
        setMinimumSize(new java.awt.Dimension(380, 500));
        setPreferredSize(new java.awt.Dimension(380, 500));

        labCorrect.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labCorrect.setText("Correct?");

        labLives.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labLives.setText("LivesLeft");

        butTopTwo.setText("Topic2");
        butTopTwo.setMaximumSize(new java.awt.Dimension(125, 65));
        butTopTwo.setMinimumSize(new java.awt.Dimension(125, 65));
        butTopTwo.setPreferredSize(new java.awt.Dimension(125, 65));
        butTopTwo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butTopTwoActionPerformed(evt);
            }
        });

        butTopOne.setText("Topic1");
        butTopOne.setMaximumSize(new java.awt.Dimension(125, 65));
        butTopOne.setMinimumSize(new java.awt.Dimension(125, 65));
        butTopOne.setPreferredSize(new java.awt.Dimension(125, 65));
        butTopOne.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butTopOneActionPerformed(evt);
            }
        });

        labNextTop.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labNextTop.setText("Pick Next Topic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(butTopOne, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(butTopTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labNextTop)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(labLives))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(labCorrect)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labCorrect)
                .addGap(45, 45, 45)
                .addComponent(labNextTop)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butTopOne, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTopTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(labLives)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butTopOneActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butTopOneActionPerformed
    {//GEN-HEADEREND:event_butTopOneActionPerformed
        // Load QuizScreen with topix chosen
        QuizScreen qs = new QuizScreen();
        qs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butTopOneActionPerformed

    private void butTopTwoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butTopTwoActionPerformed
    {//GEN-HEADEREND:event_butTopTwoActionPerformed
        // Load QuizScreen with topix chosen
        QuizScreen qs = new QuizScreen();
        qs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butTopTwoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NexTopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NexTopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NexTopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NexTopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new NexTopScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butTopOne;
    private javax.swing.JButton butTopTwo;
    private javax.swing.JLabel labCorrect;
    private javax.swing.JLabel labLives;
    private javax.swing.JLabel labNextTop;
    // End of variables declaration//GEN-END:variables
}
